version: "2"         # required to adjust maintainability checks
checks:
  method-complexity:
    config:
      threshold: 5
  method-lines:
    config:
      threshold: 100
  similar-code:
    enable: false
  identical-code:
    enable: false
plugins:
 rubocop:
    enabled: true
    channel: rubocop-0-67
 eslint:
  enabled: true
fixme:
  enabled: true
markdownlint:
  enabled: true
exclude_patterns:
- "src/config/"
- "src/index.js"
- "src/tests/*.js"