version: '2'
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
  - 'src/config/'
  - 'src/models/'
  - 'src/migrations/'
  - 'src/dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/vendor/'
  - '**/*.d.ts'
  - 'src/seeds/'
